spring:
  main:
    allow-bean-definition-overriding: 'true'

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: "127.0.0.1"
    port: 6379

server:
  port: '9010'

jwt:
  accessSecret: youcantrevealthesecretkey1234012300040
  refreshSecret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  secret: happilyeverafterhappilyeverafter

